### ISSUE TITLE
08 有几个问题需要解答一下

### ISSUE THREAD

**Issue by mofada** [shengxinjing/geektime-vue-course#7]
# 首先是`update:modelVale`

有点不太明白，为什么加了`update`就可以直接`v-model`就可以了
![image](https://user-images.githubusercontent.com/22286246/146678142-4ecce003-47ae-446f-a490-ee4e02c928f6.png)
![image](https://user-images.githubusercontent.com/22286246/146678149-87f17224-6744-4f4f-bb43-41cb6ba87024.png)

# 然后就是五星的时候貌似有点bug
![image](https://user-images.githubusercontent.com/22286246/146678196-0df6a4a4-72f1-47a3-a292-fd7c83e7fd4b.png)

**Comment by mofada** [comment]
是因为默认值就是modelValue吗？

![image](https://user-images.githubusercontent.com/22286246/146678263-3d273556-9699-424a-8cbf-325ddc517e04.png)

**Comment by shengxinjing** [comment]
算是默认了，如果有多了v-model需要处理 就需要每个都带上name的树形
星星应该是字体的问题
